import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  uz: {
    nav: {
      dashboard: 'Bosh sahifa', players: 'Futbolchilar', teams: 'Jamoalar',
      trainings: "Mashg'ulotlar", payments: "To'lovlar", stats: 'Statistika',
      subscription: 'Obuna', profile: 'Profil',
      coachPanel: 'Trener paneli', playerPanel: 'Futbolchi paneli',
      playerHome: 'Profilim', playerTrainings: "Mashg'ulotlar", playerPayment: "To'lovlar", playerMatches: "O'yinlar",
      matches: "O'yinlar",
      logout: 'Chiqish', trainer: 'Trener', player: 'Futbolchi',
    },
    dashboard: {
      title: 'Bosh sahifa', subtitle: "Umumiy ko'rsatkichlar",
      players: 'Futbolchilar', todayTraining: "Bugungi mashg'ulot",
      income: 'Oylik daromad', debtors: 'Qarzdorlar',
      hasTraining: 'Bor', noTraining: "Yo'q",
      incomeChart: "Oylik daromad (сом)", recentTrainings: "Oxirgi mashg'ulotlar",
      noData: "Ma'lumot yo'q", noTrainings: "Mashg'ulotlar yo'q",
      topPlayers: "Top o'yinchilar", scoreFormula: 'Ball = Gol×2 + Assist + Qatnashish soni',
      statusDone: 'Tugagan', statusCancelled: 'Bekor', statusPlanned: 'Rejalashtirilgan',
      currency: "сом", ball: 'ball',
      months: ['', 'Yan', 'Fev', 'Mar', 'Apr', 'May', 'Iyn', 'Iyl', 'Avg', 'Sen', 'Okt', 'Noy', 'Dek'],
    },
    players: {
      title: 'Futbolchilar', count: (n) => `${n} ta futbolchi`,
      addBtn: "Qo'shish", search: 'Qidirish...',
      noPlayers: "Futbolchilar yo'q", noResult: 'Natija topilmadi',
      editBtn: 'Tahrirlash', deleteBtn: "O'chirish", code: 'Kod',
      addTitle: "Futbolchi qo'shish", editTitle: 'Futbolchini tahrirlash',
      deleteTitle: "O'chirishni tasdiqlang", deleteConfirm: "Bu futbolchini o'chirishni istaysizmi?",
      cancel: 'Bekor', save: 'Saqlash', saving: 'Saqlanmoqda...',
      photoLabel: 'Rasm yuklash (ixtiyoriy)', firstName: 'Ism', lastName: 'Familiya',
      birthDate: "Tug'ilgan sana", position: 'Lavozim', health: "Sog'liq",
      notes: 'Izoh (ixtiyoriy)', notesPlaceholder: "Qo'shimcha ma'lumot...",
      positions: { goalkeeper: 'Darvozabon', defender: 'Himoyachi', midfielder: 'Yarim himoyachi', forward: 'Hujumchi' },
      healthStatuses: { healthy: "Sog'lom", injured: 'Jarohat', sick: 'Kasal', resting: 'Dam olmoqda' },
      error: 'Xato yuz berdi.', yosh: 'yosh',
    },
    teams: {
      title: 'Jamoalar', count: (n) => `${n} ta jamoa`,
      addBtn: "Jamoa qo'shish", noTeams: "Hali jamoa yo'q",
      noTeamsSub: "Yangi jamoa qo'shing va futbolchilarni birlang",
      firstTeam: "Birinchi jamoani qo'shish",
      manageBtn: 'Boshqarish', editBtn: 'Tahrir', deleteBtn: "O'chir",
      addTitle: 'Yangi jamoa', editTitle: 'Jamoani tahrirlash',
      deleteTitle: "O'chirishni tasdiqlang", deleteConfirm: "Bu jamoani o'chirishni istaysizmi?",
      deleteNote: "Futbolchilar jamoasiz qoladi, o'chirilmaydi.",
      cancel: 'Bekor', save: 'Saqlash', saving: 'Saqlanmoqda...',
      name: 'Jamoa nomi', namePlaceholder: 'Masalan: Asosiy jamoa, U-14, B-guruh...',
      description: 'Tavsif (ixtiyoriy)', descPlaceholder: 'Jamoa haqida qisqacha...',
      color: 'Rang', previewName: 'Jamoa nomi',
      inTeam: (n) => `Bu jamoada (${n})`, noInTeam: "Hali futbolchi yo'q",
      unassigned: (n) => `Jamoasiz (${n})`, otherTeam: (n) => `Boshqa jamoada (${n})`,
      removeBtn: 'Chiqar', addToTeamBtn: "Qo'shish", moveBtn: "Ko'chir",
      players: 'ta futbolchi', error: 'Xato yuz berdi.',
    },
    trainings: {
      title: "Mashg'ulotlar", count: (n) => `${n} ta mashg'ulot`,
      addBtn: "Qo'shish", all: 'Hammasi',
      noTrainings: "Mashg'ulotlar yo'q", noPlayers: "Futbolchilar yo'q",
      addTitle: "Mashg'ulot qo'shish", editTitle: "Mashg'ulotni tahrirlash",
      attendanceTitle: 'Davomat belgilash', deleteTitle: "O'chirishni tasdiqlang",
      deleteConfirm: "Bu mashg'ulotni o'chirishni istaysizmi?",
      cancel: 'Bekor', save: 'Saqlash', saving: 'Saqlanmoqda...', finish: 'Tugallash ✓',
      attendanceBtn: 'Davomat', editBtn: 'Tahrirlash', deleteBtn: "O'chirish",
      trainingName: "Mashg'ulot nomi", trainingNamePlaceholder: 'Misol: Texnik mashq',
      team: 'Jamoa (ixtiyoriy)', allPlayers: 'Barcha futbolchilar',
      trainingType: "Mashg'ulot turi", oneTime: 'Bir martalik', recurring: 'Doimiy jadval',
      date: 'Sana', weekDays: 'Hafta kunlari',
      startTime: 'Boshlanish vaqti', endTime: 'Tugash vaqti',
      location: 'Joy', locationPlaceholder: 'Stadion nomi',
      notes: 'Izoh', notesPlaceholder: "Qo'shimcha ma'lumot...",
      statusDone: 'Tugagan', statusCancelled: 'Bekor', statusPlanned: 'Rejalashtirilgan',
      recurringBadge: 'Doimiy',
      attOptions: { keldi: 'Keldi', kech_keldi: 'Kech keldi', kelmadi: 'Kelmadi', sababli: 'Sababli' },
      attFields: { goals: 'Gol', assists: 'Assist', distance: 'km', rating: 'Baho' },
      attenDesc: (name) => `${name} — davomat belgilash`,
      days: ['Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba', 'Yakshanba'],
      dayShort: { Dushanba: 'Du', Seshanba: 'Se', Chorshanba: 'Ch', Payshanba: 'Pa', Juma: 'Ju', Shanba: 'Sh', Yakshanba: 'Ya' },
      error: 'Xato yuz berdi.', selectDay: 'Kamida 1 ta kun tanlang.',
    },
    payments: {
      title: "To'lovlar", count: (n) => `${n} ta to'lov`,
      setFeeBtn: "To'lov belgilash", paid: "To'langan", debt: 'Qarzdorlik',
      all: 'Hammasi', pending: 'Kutilmoqda', noPayments: "To'lovlar yo'q",
      unknown: "Noma'lum", statusPaid: "To'langan", statusLate: 'Kechikkan', statusPending: 'Kutilmoqda',
      notified: "To'ladi", confirmBtn: 'Tasdiqlash', confirmTitle: "To'lovni tasdiqlash",
      confirmMsg: "Bu to'lovni to'langan deb belgilaysizmi?",
      cancel: 'Bekor', feeTitle: "Oylik to'lov belgilash",
      feeInfo: "Barcha aktiv futbolchilar uchun bir vaqtda to'lov belgilanadi",
      feeAmount: "Oylik miqdor (сом)", feeAmountPlaceholder: '5000',
      feeMonth: 'Oy', feeYear: 'Yil', feeSaveBtn: 'Hammasi uchun belgilash', feeSaving: 'Belgilanmoqda...',
      months: ['', 'Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr'],
      currency: "сом", feeSuccess: (n) => `${n} ta futbolchi uchun to'lov belgilandi!`,
    },
    stats: {
      title: 'Jamoa statistikasi', print: 'Chop etish',
      tabTop: "Top ro'yxat", tabMonthly: 'Oylik', tabAll: 'Hammasi',
      topScorers: 'Top golchilar', topAssists: 'Top assistlar', topAttendance: "Eng ko'p kelgan",
      monthly: "Oylik mashg'ulotlar", noData: "Ma'lumot yo'q", noPlayers: "Futbolchilar yo'q",
      goals: 'Gol', assists: 'Assist', attended: 'Kelgan', trainings: "ta mashg'ulot",
      months: ['', 'Yan', 'Fev', 'Mar', 'Apr', 'May', 'Iyn', 'Iyl', 'Avg', 'Sen', 'Okt', 'Noy', 'Dek'],
    },
    profile: {
      title: 'Profil', coach: 'Trener', subscription: 'Obuna',
      active: 'Faol', inactive: 'Faol emas', expires: 'Amal qilish muddati:',
      payInfo: "To'lov ma'lumotlari", viewEdit: "Ko'rish / O'zgartirish", close: 'Yopish',
      cardNumber: 'Karta', noCard: 'Karta raqami kiritilmagan',
      whatsapp: 'WhatsApp', noWhatsapp: 'WhatsApp raqami kiritilmagan',
      monthlyFee: "Oylik to'lov", noFee: 'Oylik miqdor belgilanmagan',
      cardLabel: 'Bank karta raqami', cardPlaceholder: '8600 1234 5678 9012',
      waLabel: 'WhatsApp raqami', waPlaceholder: '+996700000000',
      waHint: 'Xalqaro format: +996700000000',
      feeLabel: "Oylik to'lov miqdori (сом)", feePlaceholder: '5000',
      save: 'Saqlash', saving: 'Saqlanmoqda...', saved: 'Saqlandi!', error: 'Xato yuz berdi.',
      changePass: "Parolni o'zgartirish", change: "O'zgartirish",
      currentPass: 'Joriy parol', newPass: 'Yangi parol', confirmPass: 'Yangi parolni tasdiqlang',
      passNoMatch: "Yangi parollar mos kelmayapdi.", passShort: "Parol kamida 6 ta belgi bo'lishi kerak.",
      passChanged: "Parol muvaffaqiyatli o'zgartirildi!", logout: 'Chiqish', currency: "сом",
    },
    subscription: {
      title: 'Obuna', current: 'Joriy obuna', active: 'Faol', inactive: 'Faol emas',
      expires: 'Amal qilish muddati:', expired: 'Obuna muddati tugagan',
      recommended: 'Tavsiya', currentBadge: 'Joriy',
      upgradeTo: "Premiumga o'ting",
      upgradeDesc: "Cheksiz futbolchi qo'shish va qo'shimcha imkoniyatlar uchun admin bilan bog'laning.",
      telegram: 'Telegram orqali', call: "Qo'ng'iroq qilish",
      renewTitle: 'Obuna yangilash kerak',
      renewDesc: "Obunangiz muddati tugagan. Davom ettirish uchun admin bilan bog'laning.",
      renewBtn: "Telegram orqali bog'lanish",
      plans: {
        free: { label: 'Bepul', features: ["30 ta futbolchi", "Mashg'ulot jadvali", 'Davomat belgilash', "To'lov nazorati"], missing: ['Cheksiz futbolchilar', 'PDF hisobot', "Prioritet qo'llab-quvvatlash"] },
        premium_5: { label: 'Premium', features: ['Cheksiz futbolchilar', "Mashg'ulot jadvali", 'Davomat belgilash', "To'lov nazorati", 'Jamoa statistikasi'], missing: ['PDF hisobot', "Prioritet qo'llab-quvvatlash"] },
        premium_10: { label: 'Premium Pro', features: ['Cheksiz futbolchilar', "Mashg'ulot jadvali", 'Davomat belgilash', "To'lov nazorati", 'Jamoa statistikasi', 'PDF hisobot', "Prioritet qo'llab-quvvatlash"], missing: [] },
      },
    },
    playerHome: {
      team: 'Jamoa', coach: 'Trener',
      trainings: 'Trening', attended: 'Qatnashdi', goals: 'Gol', assists: 'Assist',
      attendance: 'Davomat', attendedCount: (a, total) => `${a} ta / ${total} ta jami`,
      recentTitle: "So'nggi trenirovkalar",
      topTitle: "Top o'yinchilar", topFormula: 'Ball = Gol×2 + Assist + Qatnashish',
      me: '(Sen)',
      statusKeldi: 'Keldi', statusKech: 'Kech keldi', statusKelmadi: 'Kelmadi',
      healthStatuses: { healthy: "Sog'lom", injured: 'Jarohat', sick: 'Kasal', resting: 'Dam olmoqda' },
      positions: { goalkeeper: 'Darvozabon', defender: 'Himoyachi', midfielder: 'Yarim himoyachi', forward: 'Hujumchi' },
      yosh: 'yosh',
    },
    playerTrainings: {
      title: "Mashg'ulotlar",
      upcoming: 'Kelayotgan', history: 'Tarix',
      noUpcoming: "Kelayotgan mashg'ulotlar yo'q", noHistory: "Mashg'ulot tarixi yo'q",
      recurring: 'Doimiy',
      attPresent: 'Qatnashgan', attLate: 'Kech keldi', attAbsent: 'Qatnashmagan', attExcused: 'Sababli',
      dayShort: { Dushanba: 'Du', Seshanba: 'Se', Chorshanba: 'Ch', Payshanba: 'Pa', Juma: 'Ju', Shanba: 'Sh', Yakshanba: 'Ya' },
      rsvpConfirm: 'Boraman', rsvpDecline: 'Bora olmayman',
      rsvpConfirmed: 'Yozildim ✓', rsvpDeclined: 'Bormayman ✗',
      rsvpError: "Xato yuz berdi. Qayta urinib ko'ring.",
    },
    matches: {
      title: "O'yinlar", nav: "O'yinlar",
      addBtn: "O'yin qo'shish", noMatches: "O'yinlar yo'q",
      all: 'Hammasi', upcoming: 'Kelayotgan', past: "O'tgan",
      home: 'Uy', away: 'Mehmon', neutral: 'Neytral',
      statusUpcoming: 'Kelayotgan', statusCompleted: 'Tugagan', statusCancelled: 'Bekor',
      opponent: 'Raqib', opponentPlaceholder: 'Raqib jamoa nomi',
      date: 'Sana', time: 'Vaqt', venue: 'Makon',
      location: 'Joy', locationPlaceholder: 'Stadion nomi',
      competition: 'Musobaqa', competitionPlaceholder: "Liga, Kubok, Do'stona...",
      team: 'Jamoa', notes: 'Izoh',
      cancel: 'Bekor', save: 'Saqlash', saving: 'Saqlanmoqda...',
      addTitle: "O'yin qo'shish", editTitle: "O'yinni tahrirlash",
      deleteConfirm: "Bu o'yinni o'chirishni istaysizmi?",
      deleteBtn: "O'chirish", editBtn: 'Tahrirlash',
      resultBtn: 'Natija', resultTitle: 'Natija kiritish',
      ourScore: 'Bizning', theirScore: 'Raqib',
      lineupTitle: 'Tarkib va statistika',
      played: "O'ynadi", goals: 'Gol', assists: 'Assist',
      statusLabel: 'Holat', win: "G'alaba", lose: "Mag'lubiyat", draw: 'Durang',
      error: 'Xato yuz berdi.',
    },
    playerMatches: {
      title: "O'yinlar",
      upcoming: 'Kelayotgan', past: "O'tgan",
      noUpcoming: "Kelayotgan o'yinlar yo'q", noPast: "O'tgan o'yinlar yo'q",
      home: 'Uy', away: 'Mehmon', neutral: 'Neytral',
      win: "G'alaba", lose: "Mag'lubiyat", draw: 'Durang',
      myStats: 'Mening statistikam', goals: 'Gol', assists: 'Assist',
      scorers: 'Golchilar', error: 'Xato yuz berdi.',
    },
    playerPayment: {
      title: "To'lovlar", currentMonth: 'Joriy oy',
      statusPaid: "To'langan", statusUnpaid: "To'lanmagan",
      pending: 'Tasdiqlash kutilmoqda', pendingHint: 'Trenerga xabar yuborildi. Trener tasdiqlashini kuting.',
      payOptions: "To'lash usulini tanlang:",
      payCard: "Karta orqali to'lash", payWa: 'WhatsApp orqali xabar berish',
      payCash: "Naqt to'lash uchun treneringiz bilan to'g'ridan-to'g'ri bog'laning",
      noCoachInfo: "Trener hali to'lov ma'lumotlarini kiritmagan. Naqt to'lang yoki trener bilan bog'laning.",
      cardLabel: 'Bank karta raqami', copyBtn: 'Nusxa olish', copied: 'Nusxa olindi!',
      amountLabel: 'Miqdor:', amountHint: "Ushbu raqamga pul o'tkazing, keyin quyidagi tugmani bosing",
      notifyBtn: "To'ladim — Trenerga xabar berish", notifying: 'Yuborilmoqda...',
      notifySuccess: "Trenerga xabar yuborildi! Tasdiqlashini kuting.", notifyError: 'Xato yuz berdi.',
      noPayment: "Joriy oy uchun to'lov hali belgilanmagan", monthlyFeeLabel: "Oylik to'lov:",
      pastDebt: "Oldingi to'lanmagan", paidHistory: "To'langan tarix",
      paidMsg: "Bu oy to'lovingiz qabul qilindi!",
      currency: 'сом',
      months: ['', 'Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr'],
      waText: (name, month, amount) => `Assalomu alaykum! Men ${name}, ${month} oylik ${amount} сом to'lovni amalga oshirdim. Tasdiqlaysizmi?`,
    },
  },

  ru: {
    nav: {
      dashboard: 'Главная', players: 'Игроки', teams: 'Команды',
      trainings: 'Тренировки', payments: 'Платежи', stats: 'Статистика',
      subscription: 'Подписка', profile: 'Профиль',
      coachPanel: 'Панель тренера', playerPanel: 'Панель игрока',
      playerHome: 'Мой профиль', playerTrainings: 'Тренировки', playerPayment: 'Платежи', playerMatches: 'Матчи',
      matches: 'Матчи',
      logout: 'Выйти', trainer: 'Тренер', player: 'Игрок',
    },
    dashboard: {
      title: 'Главная', subtitle: 'Общие показатели',
      players: 'Игроки', todayTraining: 'Тренировка сегодня',
      income: 'Месячный доход', debtors: 'Должники',
      hasTraining: 'Есть', noTraining: 'Нет',
      incomeChart: 'Месячный доход (сом)', recentTrainings: 'Последние тренировки',
      noData: 'Нет данных', noTrainings: 'Тренировок нет',
      topPlayers: 'Лучшие игроки', scoreFormula: 'Балл = Гол×2 + Ассист + Посещаемость',
      statusDone: 'Завершена', statusCancelled: 'Отменена', statusPlanned: 'Запланирована',
      currency: 'сом', ball: 'балл',
      months: ['', 'Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
    },
    players: {
      title: 'Игроки', count: (n) => `${n} игроков`,
      addBtn: 'Добавить', search: 'Поиск...',
      noPlayers: 'Игроков нет', noResult: 'Ничего не найдено',
      editBtn: 'Изменить', deleteBtn: 'Удалить', code: 'Код',
      addTitle: 'Добавить игрока', editTitle: 'Редактировать игрока',
      deleteTitle: 'Подтвердите удаление', deleteConfirm: 'Вы хотите удалить этого игрока?',
      cancel: 'Отмена', save: 'Сохранить', saving: 'Сохранение...',
      photoLabel: 'Загрузить фото (необязательно)', firstName: 'Имя', lastName: 'Фамилия',
      birthDate: 'Дата рождения', position: 'Позиция', health: 'Здоровье',
      notes: 'Примечание (необязательно)', notesPlaceholder: 'Дополнительная информация...',
      positions: { goalkeeper: 'Вратарь', defender: 'Защитник', midfielder: 'Полузащитник', forward: 'Нападающий' },
      healthStatuses: { healthy: 'Здоров', injured: 'Травма', sick: 'Болен', resting: 'Отдыхает' },
      error: 'Произошла ошибка.', yosh: 'лет',
    },
    teams: {
      title: 'Команды', count: (n) => `${n} команды`,
      addBtn: 'Добавить команду', noTeams: 'Команд ещё нет',
      noTeamsSub: 'Добавьте новую команду и объедините игроков',
      firstTeam: 'Добавить первую команду',
      manageBtn: 'Управление', editBtn: 'Изменить', deleteBtn: 'Удалить',
      addTitle: 'Новая команда', editTitle: 'Редактировать команду',
      deleteTitle: 'Подтвердите удаление', deleteConfirm: 'Вы хотите удалить эту команду?',
      deleteNote: 'Игроки останутся без команды, не будут удалены.',
      cancel: 'Отмена', save: 'Сохранить', saving: 'Сохранение...',
      name: 'Название команды', namePlaceholder: 'Например: Основной состав, U-14, Группа Б...',
      description: 'Описание (необязательно)', descPlaceholder: 'Кратко о команде...',
      color: 'Цвет', previewName: 'Название команды',
      inTeam: (n) => `В этой команде (${n})`, noInTeam: 'Игроков нет',
      unassigned: (n) => `Без команды (${n})`, otherTeam: (n) => `В другой команде (${n})`,
      removeBtn: 'Убрать', addToTeamBtn: 'Добавить', moveBtn: 'Перевести',
      players: 'игроков', error: 'Произошла ошибка.',
    },
    trainings: {
      title: 'Тренировки', count: (n) => `${n} тренировок`,
      addBtn: 'Добавить', all: 'Все',
      noTrainings: 'Тренировок нет', noPlayers: 'Игроков нет',
      addTitle: 'Добавить тренировку', editTitle: 'Редактировать тренировку',
      attendanceTitle: 'Отметить посещаемость', deleteTitle: 'Подтвердите удаление',
      deleteConfirm: 'Вы хотите удалить эту тренировку?',
      cancel: 'Отмена', save: 'Сохранить', saving: 'Сохранение...', finish: 'Завершить ✓',
      attendanceBtn: 'Посещ.', editBtn: 'Изменить', deleteBtn: 'Удалить',
      trainingName: 'Название тренировки', trainingNamePlaceholder: 'Пример: Техническая тренировка',
      team: 'Команда (необязательно)', allPlayers: 'Все игроки',
      trainingType: 'Тип тренировки', oneTime: 'Однократная', recurring: 'Постоянное расписание',
      date: 'Дата', weekDays: 'Дни недели',
      startTime: 'Время начала', endTime: 'Время окончания',
      location: 'Место', locationPlaceholder: 'Название стадиона',
      notes: 'Примечание', notesPlaceholder: 'Дополнительная информация...',
      statusDone: 'Завершена', statusCancelled: 'Отменена', statusPlanned: 'Запланирована',
      recurringBadge: 'Постоянная',
      attOptions: { keldi: 'Пришёл', kech_keldi: 'Опоздал', kelmadi: 'Не пришёл', sababli: 'По уважит.' },
      attFields: { goals: 'Гол', assists: 'Ассист', distance: 'км', rating: 'Оценка' },
      attenDesc: (name) => `${name} — посещаемость`,
      days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
      dayShort: { Dushanba: 'Пн', Seshanba: 'Вт', Chorshanba: 'Ср', Payshanba: 'Чт', Juma: 'Пт', Shanba: 'Сб', Yakshanba: 'Вс' },
      error: 'Произошла ошибка.', selectDay: 'Выберите хотя бы 1 день.',
    },
    payments: {
      title: 'Платежи', count: (n) => `${n} платежей`,
      setFeeBtn: 'Назначить платёж', paid: 'Оплачено', debt: 'Долг',
      all: 'Все', pending: 'Ожидание', noPayments: 'Платежей нет',
      unknown: 'Неизвестно', statusPaid: 'Оплачено', statusLate: 'Просрочено', statusPending: 'Ожидание',
      notified: 'Оплатил', confirmBtn: 'Подтвердить', confirmTitle: 'Подтвердить платёж',
      confirmMsg: 'Отметить этот платёж как оплаченный?',
      cancel: 'Отмена', feeTitle: 'Назначить месячный платёж',
      feeInfo: 'Платёж назначается для всех активных игроков одновременно',
      feeAmount: 'Месячная сумма (сом)', feeAmountPlaceholder: '5000',
      feeMonth: 'Месяц', feeYear: 'Год', feeSaveBtn: 'Назначить для всех', feeSaving: 'Назначается...',
      months: ['', 'Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
      currency: 'сом', feeSuccess: (n) => `Платёж назначен для ${n} игроков!`,
    },
    stats: {
      title: 'Статистика команды', print: 'Печать',
      tabTop: 'Топ-список', tabMonthly: 'По месяцам', tabAll: 'Все',
      topScorers: 'Лучшие бомбардиры', topAssists: 'Лучшие ассистенты', topAttendance: 'Наибольшее посещение',
      monthly: 'Тренировки по месяцам', noData: 'Нет данных', noPlayers: 'Игроков нет',
      goals: 'Гол', assists: 'Ассист', attended: 'Посещений', trainings: 'тренировок',
      months: ['', 'Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
    },
    profile: {
      title: 'Профиль', coach: 'Тренер', subscription: 'Подписка',
      active: 'Активна', inactive: 'Не активна', expires: 'Действует до:',
      payInfo: 'Платёжные данные', viewEdit: 'Просмотреть / Изменить', close: 'Закрыть',
      cardNumber: 'Карта', noCard: 'Номер карты не введён',
      whatsapp: 'WhatsApp', noWhatsapp: 'Номер WhatsApp не введён',
      monthlyFee: 'Месячный платёж', noFee: 'Месячная сумма не установлена',
      cardLabel: 'Номер банковской карты', cardPlaceholder: '8600 1234 5678 9012',
      waLabel: 'Номер WhatsApp', waPlaceholder: '+996700000000',
      waHint: 'Международный формат: +996700000000',
      feeLabel: 'Месячная сумма платежа (сом)', feePlaceholder: '5000',
      save: 'Сохранить', saving: 'Сохранение...', saved: 'Сохранено!', error: 'Произошла ошибка.',
      changePass: 'Изменить пароль', change: 'Изменить',
      currentPass: 'Текущий пароль', newPass: 'Новый пароль', confirmPass: 'Подтвердите новый пароль',
      passNoMatch: 'Новые пароли не совпадают.', passShort: 'Пароль должен содержать минимум 6 символов.',
      passChanged: 'Пароль успешно изменён!', logout: 'Выйти', currency: 'сом',
    },
    subscription: {
      title: 'Подписка', current: 'Текущая подписка', active: 'Активна', inactive: 'Не активна',
      expires: 'Действует до:', expired: 'Подписка истекла',
      recommended: 'Рекомендуем', currentBadge: 'Текущий',
      upgradeTo: 'Перейти на Premium',
      upgradeDesc: 'Для неограниченного количества игроков и дополнительных функций свяжитесь с администратором.',
      telegram: 'Через Telegram', call: 'Позвонить',
      renewTitle: 'Требуется обновление подписки',
      renewDesc: 'Срок вашей подписки истёк. Для продления свяжитесь с администратором.',
      renewBtn: 'Связаться через Telegram',
      plans: {
        free: { label: 'Бесплатно', features: ['30 игроков', 'Расписание тренировок', 'Отметка посещаемости', 'Контроль платежей'], missing: ['Неограниченные игроки', 'PDF отчёт', 'Приоритетная поддержка'] },
        premium_5: { label: 'Premium', features: ['Неограниченные игроки', 'Расписание тренировок', 'Отметка посещаемости', 'Контроль платежей', 'Статистика команды'], missing: ['PDF отчёт', 'Приоритетная поддержка'] },
        premium_10: { label: 'Premium Pro', features: ['Неограниченные игроки', 'Расписание тренировок', 'Отметка посещаемости', 'Контроль платежей', 'Статистика команды', 'PDF отчёт', 'Приоритетная поддержка'], missing: [] },
      },
    },
    playerHome: {
      team: 'Команда', coach: 'Тренер',
      trainings: 'Тренировки', attended: 'Посещений', goals: 'Голы', assists: 'Ассисты',
      attendance: 'Посещаемость', attendedCount: (a, total) => `${a} из ${total}`,
      recentTitle: 'Последние тренировки',
      topTitle: 'Лучшие игроки', topFormula: 'Балл = Гол×2 + Ассист + Посещаемость',
      me: '(Ты)',
      statusKeldi: 'Пришёл', statusKech: 'Опоздал', statusKelmadi: 'Не пришёл',
      healthStatuses: { healthy: 'Здоров', injured: 'Травма', sick: 'Болен', resting: 'Отдыхает' },
      positions: { goalkeeper: 'Вратарь', defender: 'Защитник', midfielder: 'Полузащитник', forward: 'Нападающий' },
      yosh: 'лет',
    },
    playerTrainings: {
      title: 'Тренировки',
      upcoming: 'Предстоящие', history: 'История',
      noUpcoming: 'Предстоящих тренировок нет', noHistory: 'Истории тренировок нет',
      recurring: 'Постоянная',
      attPresent: 'Присутствовал', attLate: 'Опоздал', attAbsent: 'Отсутствовал', attExcused: 'Уважит. причина',
      dayShort: { Dushanba: 'Пн', Seshanba: 'Вт', Chorshanba: 'Ср', Payshanba: 'Чт', Juma: 'Пт', Shanba: 'Сб', Yakshanba: 'Вс' },
      rsvpConfirm: 'Приду', rsvpDecline: 'Не приду',
      rsvpConfirmed: 'Записался ✓', rsvpDeclined: 'Не приду ✗',
      rsvpError: 'Произошла ошибка. Попробуйте снова.',
    },
    matches: {
      title: 'Матчи', nav: 'Матчи',
      addBtn: 'Добавить матч', noMatches: 'Матчей нет',
      all: 'Все', upcoming: 'Предстоящие', past: 'Прошедшие',
      home: 'Дома', away: 'Гости', neutral: 'Нейтрал',
      statusUpcoming: 'Предстоящий', statusCompleted: 'Завершён', statusCancelled: 'Отменён',
      opponent: 'Соперник', opponentPlaceholder: 'Название команды соперника',
      date: 'Дата', time: 'Время', venue: 'Поле',
      location: 'Место', locationPlaceholder: 'Название стадиона',
      competition: 'Соревнование', competitionPlaceholder: 'Лига, Кубок, Товарищеский...',
      team: 'Команда', notes: 'Примечание',
      cancel: 'Отмена', save: 'Сохранить', saving: 'Сохранение...',
      addTitle: 'Добавить матч', editTitle: 'Редактировать матч',
      deleteConfirm: 'Вы хотите удалить этот матч?',
      deleteBtn: 'Удалить', editBtn: 'Изменить',
      resultBtn: 'Результат', resultTitle: 'Записать результат',
      ourScore: 'Наши', theirScore: 'Соперник',
      lineupTitle: 'Состав и статистика',
      played: 'Играл', goals: 'Гол', assists: 'Ассист',
      statusLabel: 'Статус', win: 'Победа', lose: 'Поражение', draw: 'Ничья',
      error: 'Произошла ошибка.',
    },
    playerMatches: {
      title: 'Матчи',
      upcoming: 'Предстоящие', past: 'Прошедшие',
      noUpcoming: 'Предстоящих матчей нет', noPast: 'Прошедших матчей нет',
      home: 'Дома', away: 'Гости', neutral: 'Нейтрал',
      win: 'Победа', lose: 'Поражение', draw: 'Ничья',
      myStats: 'Моя статистика', goals: 'Гол', assists: 'Ассист',
      scorers: 'Голевые действия', error: 'Произошла ошибка.',
    },
    playerPayment: {
      title: 'Платежи', currentMonth: 'Текущий месяц',
      statusPaid: 'Оплачено', statusUnpaid: 'Не оплачено',
      pending: 'Ожидание подтверждения', pendingHint: 'Тренер уведомлён. Ожидайте подтверждения.',
      payOptions: 'Выберите способ оплаты:',
      payCard: 'Оплата картой', payWa: 'Отправить сообщение WhatsApp',
      payCash: 'Для оплаты наличными обратитесь напрямую к тренеру',
      noCoachInfo: 'Тренер ещё не указал платёжные данные. Оплатите наличными или обратитесь к тренеру.',
      cardLabel: 'Номер банковской карты', copyBtn: 'Копировать', copied: 'Скопировано!',
      amountLabel: 'Сумма:', amountHint: 'Переведите на этот номер, затем нажмите кнопку ниже',
      notifyBtn: 'Оплатил — Уведомить тренера', notifying: 'Отправляется...',
      notifySuccess: 'Тренер уведомлён! Ожидайте подтверждения.', notifyError: 'Произошла ошибка.',
      noPayment: 'Платёж за текущий месяц ещё не назначен', monthlyFeeLabel: 'Ежемесячный платёж:',
      pastDebt: 'Прошлые долги', paidHistory: 'История оплат',
      paidMsg: 'Ваш платёж за этот месяц принят!',
      currency: 'сом',
      months: ['', 'Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
      waText: (name, month, amount) => `Здравствуйте! Я ${name}, оплатил ${amount} сом за ${month}. Подтвердите, пожалуйста?`,
    },
  },
};

const ThemeContext = createContext(null);

export function ThemeProvider({ children }) {
  const [dark, setDarkState] = useState(() => localStorage.getItem('theme') !== 'light');
  const [lang, setLangState] = useState(() => localStorage.getItem('lang') || 'ru');

  const setDark = useCallback((val) => {
    setDarkState(val);
    localStorage.setItem('theme', val ? 'dark' : 'light');
  }, []);

  const setLang = useCallback((val) => {
    setLangState(val);
    localStorage.setItem('lang', val);
  }, []);

  return (
    <ThemeContext.Provider value={{ dark, setDark, lang, setLang, t: translations[lang] }}>
      {children}
    </ThemeContext.Provider>
  );
}

export const useTheme = () => useContext(ThemeContext);
